// Importing createSlice from Redux Toolkit, which simplifies creating Redux slices
import { createSlice } from "@reduxjs/toolkit";

// Creating a Redux slice named "counter" using createSlice
const counterSlice = createSlice({
  // The name of the slice, used to identify it in the Redux store
  name: "counter",
  // The initial state of the slice, defining the starting value of the counter
  initialState: {
    value: 0, // The counter starts at 0
  },
  // Reducers define how the state can be updated via actions
  reducers: {
    // Increment reducer: increases the counter value by 1
    increment: (state) => {
      // Redux Toolkit allows direct state mutation (handled by Immer under the hood)
      state.value += 1; // Updates the value property in the state
    },
    // Decrement reducer: decreases the counter value by 1
    decrement: (state) => {
      state.value -= 1; // Updates the value property in the state
    },
  },
});

// Exporting the action creators (increment and decrement) generated by createSlice
export const { increment, decrement } = counterSlice.actions;

// Exporting the reducer function to be used in the Redux store
export default counterSlice.reducer;
